version: "3.9"

services:
  java_app:
    container_name: prueba-neoris
    image: prueba-neoris-1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/NEORIS
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:12
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: 